framework:
    notifier:
        chatter_transports:
            main: '%env(SLACK_DSN)% || %env(TELEGRAM_DSN)%'
            roundrobin: '%env(SLACK_DSN)% && %env(TELEGRAM_DSN)%'
            
        texter_transports:
            expo: '%env(EXPO_DSN)%'
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
